server:
  port: 8002
spring:
  application:
    name: xc-item-detail-consumer
eureka:
  instance:
    instance-id: xc-item-detail-consumer
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://60.205.207.9:6001/eureka/
feign:
  hystrix:
    enabled: true
