server:
  port: 8001
spring:
  application:
    name: xc-shopping-consumer
eureka:
  instance:
    instance-id: xc-shopping-consumer
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://60.205.207.9:6001/eureka/
feign:
  hystrix:
    enabled: true
---
spring:
  zipkin:
    base-url: http://60.205.207.9:7777
  sleuth:
    sampler:
       percentage: 1.0
logging:
    level: info