server:
  port: 7051
spring:
  application:
    name: xc-item-detail-provider
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
  http:
      multipart:
        enabled: true   # 启用http上传处理
        max-file-size: 100MB # 设置单个文件的最大长度
        max-request-size: 100MB # 设置最大的请求文件的大小
        file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
  rabbitmq:
      host: 47.94.201.44
      port: 5672
      username: xiaocheng
      password:  xiaocheng
      virtual-host: /xiaocheng
      publisher-confirms: true
      publisher-returns: true
      listener:
        simple:
          prefetch: 1
  datasource:
    url: jdbc:mysql://localhost:3306/vip?charecterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
eureka:
  instance:
    instance-id: xc-item-detail-provider
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://101.132.139.58:6001/eureka/
mybatis:
  mapper-locations: classpath:Mapper/*.xml