server:
  port: 8002
spring:
  application:
    name: xc-order-consumer
eureka:
  instance:
    instance-id: xc-order-consumer
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://101.132.139.58:6001/eureka/
feign:
  hystrix:
    enabled: true
---
spring:
  zipkin:
    base-url: http://101.132.139.58:7777
  sleuth:
    sampler:
       percentage: 1.0
logging:
    level: info