server:
  port: 7001
spring:
  application:
    name: xc-item-show-provider
eureka:
  instance:
    instance-id: xc-item-show-provider
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://60.205.207.9:6001/eureka/
---
spring:
  zipkin:
    base-url: http://60.205.207.9:7777
  sleuth:
    sampler:
       percentage: 1.0
logging:
    level: info