server:
  port: 8001
spring:
  application:
    name: xc-item-show-consumer
  datasource:
    url: jdbc:mysql://localhost:3306/vip?charecterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc:
    static-path-pattern: /static/**
eureka:
  instance:
    instance-id: xc-item-show-consumer
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://101.132.139.58:6001/eureka/
feign:
  hystrix:
    enabled: true
---
spring:
  zipkin:
    base-url: http://101.132.139.58:7777
  sleuth:
    sampler:
       percentage: 1.0
logging:
    level: info
---
spring:
  thymeleaf:
      prefix: classpath:/static/html/
      suffix: .html